#! /bin/sh

# This script converts *.dis files to the PNG ones.
#
# Usage ./dis2ps files
#
# requires the "dis2gp" tool to be in a current working directory
# and (obviously) the to be "gnuplot" somewhere in $PATH
#
# (C) Jiri Brozovsky

for aa in $@; do \
echo "set term png
set output \"$aa.png\"
set grid 
plot \"-\" title \"$aa\" w l  
`./dis2gp $aa`" |gnuplot ; done
